 function weather1click() {
    document.getElementById("WeatherInformation").innerHTML="Tempreture: 35C";
    document.getElementById("WeatherCity").innerHTML="City: Tehran";
 }

 function weather2click() {
    document.getElementById("WeatherInformation").innerHTML="Tempreture: 20C";
    document.getElementById("WeatherCity").innerHTML="City: Tbilisi";
 }

 function weather3click() {
    document.getElementById("WeatherInformation").innerHTML="Tempreture: 45C";
    document.getElementById("WeatherCity").innerHTML="City: Istanbul";
 }